### ISSUE TITLE
Kill error 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pylammpsmpi#10]
On mybinder I get the following error: 

```
Exception ignored in: <function LammpsLibrary.__del__ at 0x7efd0c77a290>
Traceback (most recent call last):
  File "/home/jovyan/pylammpsmpi/lammps.py", line 585, in __del__
  File "/home/jovyan/pylammpsmpi/lammps.py", line 579, in close
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 1790, in kill
AttributeError: 'NoneType' object has no attribute 'SIGKILL'
```

**Comment by srmnitc** [comment]
I think what happens is that job.close from lammps side kills the subprocess call automatically
